---
services:
  - docker

jobs:
  include:
    - stage: 'Build systemd-libvirt'
      if: type = pull_request
      script:
        - cd el7
        - docker build jenkins-agent-lago-mock
    - stage: 'Deploy systemd-libvirt'
      if: type = push
      script: >
        make DOCKERHUB_PW=${DOCKERHUB_PW}
        DOCKERHUB_UNAME=${DOCKERHUB_UNAME}
        jenkins-agent-lago-mock
